--- #YAML:1.0
name:               Config-Pico
version:            0.01
abstract:           Pure Perl Interpretative COnfiguration = do "config.pl"
author:
    - Yusuke Kawasaki
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.55
build_requires:
    Test::More:  0
requires:
    Carp:        0
    Exporter:    0
    File::Spec:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
